// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IAFuv9C6Dk5EoTiWI528j8upxYSgNX0',
    appId: '1:530683869177:web:228d1ef51d2c19f5abaf28',
    messagingSenderId: '530683869177',
    projectId: 'flutter-tutorial-790e3',
    authDomain: 'flutter-tutorial-790e3.firebaseapp.com',
    storageBucket: 'flutter-tutorial-790e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAau5WhjfUusbJyUtciTAEnbD6-YumiYaw',
    appId: '1:530683869177:android:68298158256970a5abaf28',
    messagingSenderId: '530683869177',
    projectId: 'flutter-tutorial-790e3',
    storageBucket: 'flutter-tutorial-790e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk50pTGFMkMoZBwoAEZ01VjVjtFH7hnmE',
    appId: '1:530683869177:ios:7eebbeef1deff0e2abaf28',
    messagingSenderId: '530683869177',
    projectId: 'flutter-tutorial-790e3',
    storageBucket: 'flutter-tutorial-790e3.appspot.com',
    iosClientId: '530683869177-92alrr0ovtn4ds1k8814ging8eco4v9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseKadai',
  );
}
